version: '3'
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    command:
      tail -f /dev/null
    networks:
      - some-net
    # Para entrar a flask, entramos con 0.0.0.0:8082 desde afuera del docker
    ports:
      - 8082:4000
  
  mysql_db:
    image: mysql
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mario
      MYSQL_PASSWORD: mario     
    ports: 
      - 3308:3306
    networks:
      - some-net
    

networks:
  some-net:
    driver: bridge

